modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="whooshy_things"
version="1.0.0"
displayName="Whooshy Things"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="mrasm, MCreator"

[[dependencies.whooshy_things]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




